"""create program tables

Revision ID: 0fddbf0aaeae
Revises: be32adb470fd
Create Date: 2019-06-23 11:15:13.095885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fddbf0aaeae'
down_revision = 'be32adb470fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('program_image', sa.String(), nullable=True),
    sa.Column('description', sa.JSON(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('application_deadline', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('curriculum', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facilitators',
    sa.Column('facilitator_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['facilitator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('facilitator_id', 'program_id')
    )
    op.create_table('learners',
    sa.Column('learner_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('learner_id', 'program_id')
    )
    op.create_table('organizers',
    sa.Column('organizer_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('organizer_id', 'program_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organizers')
    op.drop_table('learners')
    op.drop_table('facilitators')
    op.drop_table('programs')
    # ### end Alembic commands ###
