"""empty message

Revision ID: 6658188d8d69
Revises: 0fddbf0aaeae
Create Date: 2019-06-26 14:10:06.191163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6658188d8d69'
down_revision = '0fddbf0aaeae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(length=60), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.create_table('user_permissions',
    sa.Column('permissions_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permissions_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('permissions_id', 'user_id')
    )
    op.add_column('programs', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('programs', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('programs', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('programs', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'role_id')
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'deleted')
    op.drop_column('users', 'created_at')
    op.drop_column('programs', 'updated_at')
    op.drop_column('programs', 'deleted_at')
    op.drop_column('programs', 'deleted')
    op.drop_column('programs', 'created_at')
    op.drop_table('user_permissions')
    op.drop_table('permissions')
    op.drop_table('roles')
    # ### end Alembic commands ###
